# Generated by Django 2.1.4 on 2018-12-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181220_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='music.Sheet'),
        ),
    ]
